name: halli-galli-test
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  app-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm insatall, test
        run: npm install

      - name: Set environment variables from Secrets
        run: |
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> $GITHUB_ENV
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> $GITHUB_ENV
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV

      - name: Run test
        run: npm test
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

      - name: Build Docker image
        if: success()
        run: docker build -t halli-galli -f docker/dockerfile-halli .
      - name: Login to Docker Hub 
        if: success()
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Push Docker image
        if: success()
        run: docker push halli-galli